import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { BookOpen, CalendarDays, ListChecks, ClipboardList, LayoutDashboard, Type, CheckSquare, Minus, Square, Download, Plus, Trash2, Settings2, Sparkles, ChevronLeft, ChevronRight, X, Grid2X2 } from "lucide-react";
import { jsPDF } from "jspdf";
import "./styles.css";

const I = { BookOpen, CalendarDays, ListChecks, ClipboardList, LayoutDashboard, Type, CheckSquare, Minus, Square, Sparkles };
const L = {
  en: { studio: "Template Studio", templates: "Templates", elements: "Elements", notebook: "Linked Notebook", annual: "Annual Planner", tasks: "Task List", weekly: "Weekly Planner", layout: "Layout", text: "Text", check: "Checklist", line: "Divider", box: "Box", icon: "Lucide Icon", preview: "Live Preview", config: "Configuration", size: "Paper size", orientation: "Orientation", paper: "Paper", accent: "Accent", style: "Page style", tabs: "Side tabs", minimal: "Minimal", sections: "Sections", add: "Add section", cover: "Cover page", numbers: "Page numbers", year: "Year", week: "Week starts", monday: "Monday", sunday: "Sunday", density: "Calendar density", comfortable: "Comfortable", spacious: "Spacious", compact: "Compact", weeknumbers: "Week numbers", notes: "Notes area", rows: "Task rows", priority: "Priority", due: "Due date", export: "Export PDF", ready: "Ready", selected: "Selected element", content: "Content", width: "Width", height: "Height", remove: "Delete", choose: "Choose a template", build: "Build a Goodnotes-ready digital template.", descN: "Hyperlinked sections, tabs and note pages.", descA: "Automatic year and monthly calendars.", descT: "Clean task list with priorities and due dates.", descW: "Weekly overview with planning and notes.", noElements: "Add elements from the sidebar.", lang: "Language" },
  de: { studio: "Template Studio", templates: "Vorlagen", elements: "Elemente", notebook: "Verknüpftes Notizbuch", annual: "Jahresplaner", tasks: "Aufgabenliste", weekly: "Wochenplaner", layout: "Layout", text: "Text", check: "Checkliste", line: "Trenner", box: "Box", icon: "Lucide-Symbol", preview: "Live-Vorschau", config: "Konfiguration", size: "Papierformat", orientation: "Ausrichtung", paper: "Papier", accent: "Akzent", style: "Seitenstil", tabs: "Seitentabs", minimal: "Minimal", sections: "Bereiche", add: "Bereich hinzufügen", cover: "Titelseite", numbers: "Seitenzahlen", year: "Jahr", week: "Wochenstart", monday: "Montag", sunday: "Sonntag", density: "Kalenderdichte", comfortable: "Komfortabel", spacious: "Großzügig", compact: "Kompakt", weeknumbers: "Kalenderwochen", notes: "Notizbereich", rows: "Aufgabenzeilen", priority: "Priorität", due: "Fälligkeitsdatum", export: "PDF exportieren", ready: "Bereit", selected: "Ausgewähltes Element", content: "Inhalt", width: "Breite", height: "Höhe", remove: "Löschen", choose: "Vorlage wählen", build: "Digitale Goodnotes-Vorlage erstellen.", descN: "Verknüpfte Bereiche, Tabs und Notizseiten.", descA: "Automatisches Jahr und Monatskalender.", descT: "Klare Aufgabenliste mit Prioritäten und Fälligkeit.", descW: "Wochenübersicht mit Planung und Notizen.", noElements: "Elemente über die Seitenleiste hinzufügen.", lang: "Sprache" },
  es: { studio: "Template Studio", templates: "Plantillas", elements: "Elementos", notebook: "Notebook enlazado", annual: "Planificador anual", tasks: "Lista de tareas", weekly: "Planificador semanal", layout: "Diseño", text: "Texto", check: "Checklist", line: "Separador", box: "Caja", icon: "Icono Lucide", preview: "Vista previa", config: "Configuración", size: "Tamaño de papel", orientation: "Orientación", paper: "Papel", accent: "Acento", style: "Estilo de página", tabs: "Pestañas laterales", minimal: "Minimal", sections: "Secciones", add: "Añadir sección", cover: "Portada", numbers: "Números de página", year: "Año", week: "Inicio de semana", monday: "Lunes", sunday: "Domingo", density: "Densidad del calendario", comfortable: "Cómoda", spacious: "Amplia", compact: "Compacta", weeknumbers: "Números de semana", notes: "Zona de notas", rows: "Filas de tareas", priority: "Prioridad", due: "Fecha límite", export: "Exportar PDF", ready: "Listo", selected: "Elemento seleccionado", content: "Contenido", width: "Ancho", height: "Alto", remove: "Eliminar", choose: "Elegir plantilla", build: "Crea una plantilla digital lista para Goodnotes.", descN: "Secciones, pestañas y páginas enlazadas.", descA: "Año y calendarios mensuales automáticos.", descT: "Lista de tareas con prioridades y fechas.", descW: "Vista semanal con planificación y notas.", noElements: "Añade elementos desde la barra lateral.", lang: "Idioma" }
};
const tr = (l, k) => L[l][k] || L.en[k] || k;
const presets = { Forest: ["#40916c", "#d0f4de"], Ocean: ["#3d5a80", "#cddafd"], Earth: ["#7f4f24", "#fff8f0"], Coral: ["#ff4d6d", "#fff1f4"], Mint: ["#d0f4de", "#f7fffa"], Lavender: ["#cddafd", "#fafbff"] };
const base = { notebook: { name: "My Notebook", size: "A4", orientation: "portrait", style: "ruled", accent: "#40916c", paper: "#d0f4de", tabs: true, cover: true, numbers: true, sections: [["Personal", 10], ["Work", 10], ["Projects", 10], ["Notes", 10]], elements: [] }, annual: { name: "Annual Planner", year: new Date().getFullYear(), size: "A4", orientation: "landscape", week: "monday", density: "comfortable", accent: "#40916c", paper: "#d0f4de", weeknumbers: true, notes: true, elements: [] }, tasks: { name: "Task List", size: "A4", orientation: "portrait", rows: 16, priority: true, due: true, accent: "#40916c", paper: "#d0f4de", elements: [] }, weekly: { name: "Weekly Planner", size: "A4", orientation: "landscape", week: "monday", notes: true, accent: "#40916c", paper: "#d0f4de", elements: [] } };
const meta = { notebook: [BookOpen, "notebook", "descN"], annual: [CalendarDays, "annual", "descA"], tasks: [ListChecks, "tasks", "descT"], weekly: [ClipboardList, "weekly", "descW"] };
const sizes = { A4: [210, 297], A5: [148, 210], Letter: [216, 279] };
const mn = (y, m) => new Date(y, m, 1).toLocaleString("en-US", { month: "long" });
const md = (y, m) => new Date(y, m + 1, 0).getDate();
const off = (y, m, w) => { let d = new Date(y, m, 1).getDay(); return w === "sunday" ? d : (d + 6) % 7 };
const rgb = h => { h = h.replace("#", ""); return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)] };

function PDFText(p, s, x, y, z = 10, c = [40, 40, 40], b = false, a = "left") { p.setFont("helvetica", b ? "bold" : "normal"); p.setFontSize(z); p.setTextColor(...c); p.text(s, x, y, { align: a }) }
function brand(p, w, h) { PDFText(p, "dienix", w - 10, h - 7, 7, [125, 125, 125], false, "right") }
function paper(p, w, h, s, c) { p.setFillColor(...rgb(c)); p.rect(0, 0, w, h, "F"); p.setDrawColor(220); p.setLineWidth(.15); if (s === "ruled" || s === "grid") for (let y = 25; y < h - 15; y += 7)p.line(13, y, w - 13, y); if (s === "grid") for (let x = 13; x < w - 13; x += 7)p.line(x, 20, x, h - 15); if (s === "dotted") { p.setFillColor(185); for (let y = 22; y < h - 15; y += 6)for (let x = 14; x < w - 13; x += 6)p.circle(x, y, .3, "F") } }
function elementsPDF(p, es) { es.forEach(e => { let x = e.x, y = e.y, w = e.w, h = e.h, c = rgb(e.color); p.setDrawColor(...c); p.setTextColor(...c); if (e.type === "text") PDFText(p, e.content, x, y + 5, e.size, c, e.bold); if (e.type === "check") { p.rect(x, y, 5, 5); PDFText(p, e.content, x + 8, y + 4, 8, c) } if (e.type === "line") p.line(x, y, x + w, y); if (e.type === "box") p.roundedRect(x, y, w, h, 2, 2); if (e.type === "icon") { p.circle(x + 4, y + 4, 3); PDFText(p, "★", x + 4, y + 6, 6, c, true, "center") } }) }

function exportNotebook(c) { let [bw, bh] = sizes[c.size], land = c.orientation === "landscape", w = land ? bh : bw, h = land ? bw : bh, p = new jsPDF({ unit: "mm", format: [w, h], orientation: land ? "landscape" : "portrait" }); let total = 2 + c.sections.reduce((n, s) => n + s[1], 0); p.setFillColor(250, 237, 244); p.rect(0, 0, w, h, "F"); PDFText(p, c.name.toUpperCase(), 14, h / 2, 25, [35, 35, 35], true); PDFText(p, "A linked digital notebook for Goodnotes", 15, h / 2 + 12, 9, [100, 100, 100]); brand(p, w, h); p.addPage([w, h]); PDFText(p, "INDEX", 14, 22, 21, [35, 35, 35], true); let y = 42, target = 3; c.sections.forEach((s, i) => { p.setFillColor(...rgb(c.accent)); p.roundedRect(14, y - 6, w - 28, 11, 2, 2, "F"); PDFText(p, `${i + 1}. ${s[0]}`, 20, y + 1, 9, [255, 255, 255], true); p.link(14, y - 6, w - 28, 11, { pageNumber: target }); y += 17; target += s[1] }); brand(p, w, h); let pg = 3; c.sections.forEach((s, i) => { for (let n = 0; n < s[1]; n++) { p.addPage([w, h]); paper(p, w, h, c.style, c.paper); p.setFillColor(...rgb(c.accent)); p.rect(0, 0, w, 3, "F"); PDFText(p, s[0], 14, 17, 11, [55, 55, 55], true); if (c.tabs) { let th = 14, ty = 22 + i * th; p.setFillColor(...rgb(c.accent)); p.roundedRect(w - 12, ty, 9, 12, 1, 1, "F"); PDFText(p, String(i + 1), w - 7.5, ty + 8, 5, [255, 255, 255], true, "center"); p.link(w - 13, ty, 11, 12, { pageNumber: 3 + c.sections.slice(0, i).reduce((a, x) => a + x[1], 0) }) } elementsPDF(p, c.elements); if (c.numbers) PDFText(p, String(pg), w / 2, h - 7, 6, [120, 120, 120], false, "center"); p.link(10, h - 14, 25, 8, { pageNumber: 2 }); if (pg > 3) p.link(w / 2 - 18, h - 14, 14, 8, { pageNumber: pg - 1 }); if (pg < total) p.link(w / 2 + 4, h - 14, 14, 8, { pageNumber: pg + 1 }); brand(p, w, h); pg++ } }); p.save(c.name.replaceAll(" ", "-") + ".pdf") }
function exportAnnual(c) { let [bw, bh] = sizes[c.size], land = c.orientation === "landscape", w = land ? bh : bw, h = land ? bw : bh, p = new jsPDF({ unit: "mm", format: [w, h], orientation: land ? "landscape" : "portrait" }); PDFText(p, String(c.year), 14, h / 2, 34, [35, 35, 35], true); PDFText(p, "ANNUAL PLANNER", 16, h / 2 + 13, 12, [90, 90, 90], true); brand(p, w, h); p.addPage([w, h]); PDFText(p, `${c.year} OVERVIEW`, 14, 22, 20, [35, 35, 35], true); let cw = (w - 35) / 3, ch = (h - 55) / 4; for (let m = 0; m < 12; m++) { let x = 14 + (m % 3) * cw, y = 34 + Math.floor(m / 3) * ch; p.setFillColor(252, 245, 248); p.roundedRect(x, y, cw - 6, ch - 6, 2, 2, "F"); PDFText(p, mn(c.year, m).toUpperCase(), x + 4, y + 9, 8, [55, 55, 55], true); p.link(x, y, cw - 6, ch - 6, { pageNumber: m + 3 }) } brand(p, w, h); for (let m = 0; m < 12; m++) { p.addPage([w, h]); PDFText(p, mn(c.year, m).toUpperCase(), 14, 20, 20, [40, 40, 40], true); let gx = 12, gy = 29, gw = w - 24, gh = h - 48, cw2 = gw / 7, ch2 = (gh - 8) / 6; let ls = c.week === "sunday" ? ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"] : ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]; p.setFillColor(246, 239, 243); p.rect(gx, gy, gw, 8, "F"); p.setDrawColor(205); for (let x = 0; x <= 7; x++)p.line(gx + x * cw2, gy, gx + x * cw2, gy + gh); for (let r = 0; r <= 7; r++)p.line(gx, gy + 8 + r * ch2, gx + gw, gy + 8 + r * ch2); ls.forEach((d, i) => PDFText(p, d, gx + i * cw2 + cw2 / 2, gy + 5, 6, [100, 100, 100], true, "center")); let o = off(c.year, m, c.week), days = md(c.year, m); for (let d = 1; d <= days; d++) { let q = o + d - 1, x = gx + (q % 7) * cw2, y = gy + 8 + Math.floor(q / 7) * ch2; PDFText(p, String(d), x + 3, y + 6, 7, [65, 65, 65], true) } if (c.notes) { p.setDrawColor(...rgb(c.accent)); p.roundedRect(12, h - 15, gw, 7, 2, 2); PDFText(p, "NOTES", 16, h - 10, 5, [100, 80, 90], true) } p.link(10, h - 14, 25, 8, { pageNumber: 2 }); if (m > 0) p.link(w / 2 - 18, h - 14, 14, 8, { pageNumber: m + 2 }); if (m < 11) p.link(w / 2 + 4, h - 14, 14, 8, { pageNumber: m + 4 }); brand(p, w, h) } p.save(c.name.replaceAll(" ", "-") + "-" + c.year + ".pdf") }
function exportTasks(c) { let [bw, bh] = sizes[c.size], land = c.orientation === "landscape", w = land ? bh : bw, h = land ? bw : bh, p = new jsPDF({ unit: "mm", format: [w, h], orientation: land ? "landscape" : "portrait" }); paper(p, w, h, "blank", c.paper); PDFText(p, c.name, 15, 22, 22, [40, 40, 40], true); PDFText(p, "TASK LIST", 15, 30, 8, [120, 120, 120]); let y = 44; for (let i = 0; i < c.rows; i++) { p.rect(15, y, 6, 6); p.line(25, y + 6, w - 15, y + 6); if (c.priority) p.circle(w - 20, y + 3, 2); y += 12 } elementsPDF(p, c.elements); brand(p, w, h); p.save(c.name.replaceAll(" ", "-") + ".pdf") }
function exportWeekly(c) { let [bw, bh] = sizes[c.size], land = c.orientation === "landscape", w = land ? bh : bw, h = land ? bw : bh, p = new jsPDF({ unit: "mm", format: [w, h], orientation: land ? "landscape" : "portrait" }); paper(p, w, h, "blank", c.paper); PDFText(p, c.name, 15, 20, 20, [40, 40, 40], true); let ls = c.week === "sunday" ? ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"] : ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"], gx = 12, gy = 30, gw = w - 24, cw = gw / 7; ls.forEach((d, i) => { let x = gx + i * cw; p.setFillColor(246, 239, 243); p.rect(x, gy, cw, 8, "F"); PDFText(p, d, x + cw / 2, gy + 5, 6, [100, 100, 100], true, "center"); p.rect(x, gy + 8, cw, 115) }); if (c.notes) { p.roundedRect(12, h - 35, gw, 18, 2, 2); PDFText(p, "NOTES", 16, h - 29, 6, [100, 100, 100], true) } elementsPDF(p, c.elements); brand(p, w, h); p.save(c.name.replaceAll(" ", "-") + ".pdf") }

function Element({ e }) { let s = { left: e.x + "%", top: e.y + "%", width: e.w + "%", height: e.h + "%", color: e.color, fontSize: e.size + "px" }; if (e.type === "text") return <div className={"el text " + (e.bold ? "bold" : "")} style={s}>{e.content}</div>; if (e.type === "check") return <div className="el check" style={s}><span /> {e.content}</div>; if (e.type === "line") return <div className="el line" style={{ ...s, background: e.color }} />; if (e.type === "box") return <div className="el box" style={{ ...s, borderColor: e.color }} />; return <div className="el icon" style={s}>★</div> }
function Preview({ type, cfg, month }) {
  const style = { background: cfg.paper };
  const accent = cfg.accent;
  const days = cfg.week === "sunday" ? ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"] : ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"];

  if (type === "notebook") return <div className="page notebook premium-paper" style={style}>
    <div className="premium-top" style={{ background: accent }} />
    <div className="nb-brand">dienix</div>
    <div className="nb-title"><h3>{cfg.sections[0]?.[0] || "Notebook"}</h3><small>LINKED DIGITAL NOTEBOOK</small></div>
    <div className={"lines " + cfg.style} />
    <div className="nb-meta"><span>01</span><span>NOTES</span></div>
    {cfg.tabs && <div className="tabs">{cfg.sections.map((s, i) => <span key={i} style={{ background: accent }}>{String(i + 1).padStart(2, "0")}</span>)}</div>}
    <div className="nb-footer"><span>INDEX</span><span>‹</span><span>›</span><span>dienix</span></div>
    {cfg.elements.map(e => <Element key={e.id} e={e} />)}
  </div>;

  if (type === "annual") {
    const o = off(cfg.year, month, cfg.week);
    const cells = Array.from({ length: 42 }, (_, i) => { let d = i - o + 1; return d > 0 && d <= md(cfg.year, month) ? d : "" });
    return <div className="page annual premium-paper" style={style}>
      <div className="premium-top" style={{ background: accent }} />
      <div className="planner-kicker">ANNUAL PLANNER · DEMO</div>
      <div className="annual-title"><h3>{mn(cfg.year, month)}</h3><span>{cfg.year}</span></div>
      <div className="annual-subtitle">PLAN · ORGANIZE · WRITE · REVIEW</div>
      <div className="dow">{days.map(x => <b key={x}>{x}</b>)}</div>
      <div className={"cal " + cfg.density}>{cells.map((d, i) => <span key={i}>{d && <><b>{d}</b><i /></>}</span>)}</div>
      {cfg.notes && <div className="notes premium-notes"><b>NOTES</b><span /></div>}
      <div className="planner-signature">dienix</div>
      {cfg.elements.map(e => <Element key={e.id} e={e} />)}
    </div>;
  }

  if (type === "tasks") return <div className="page tasks premium-paper" style={style}>
    <div className="premium-top" style={{ background: accent }} />
    <div className="planner-kicker">PRODUCTIVITY · DEMO</div>
    <div className="tasks-title"><h3>{cfg.name}</h3><small>PLAN · PRIORITIZE · COMPLETE</small></div>
    <div className="task-date-card"><b>01</b><span>MON</span></div>
    <div className="priority-title">TOP PRIORITIES</div>
    <div className="priority-strip"><div /><div /><div /></div>
    <div className="task-head"><span>TASK</span>{cfg.priority && <span>PRIORITY</span>}{cfg.due && <span>DUE</span>}</div>
    <div className="task-list">{Array.from({ length: Math.min(cfg.rows, 12) }, (_, i) => <div className="task" key={i}><i /><span /><>{cfg.priority && <em>•</em>}{cfg.due && <small>/</small>}</></div>)}</div>
    <div className="task-bottom-premium"><div><b>FOCUS</b><span /></div><div><b>NOTES</b><span /></div></div>
    <div className="planner-signature">dienix</div>
    {cfg.elements.map(e => <Element key={e.id} e={e} />)}
  </div>;

  return <div className="page weekly premium-paper" style={style}>
    <div className="premium-top" style={{ background: accent }} />
    <div className="planner-kicker">WEEKLY PLANNER · DEMO</div>
    <div className="weekly-title"><h3>{cfg.name}</h3><small>WEEKLY OVERVIEW</small></div>
    <div className="week-badge"><b>WEEK</b><span>01</span></div>
    <div className="week premium-week">{days.map(d => <div key={d}><b style={{ background: accent }}>{d}</b><span /><i /><em /></div>)}</div>
    <div className="weekly-bottom-premium"><div><b>FOCUS</b><span /></div><div><b>NOTES</b><span /></div></div>
    <div className="planner-signature">dienix</div>
    {cfg.elements.map(e => <Element key={e.id} e={e} />)}
  </div>
}

function App() {
  const [lang, setLang] = useState("en"), [type, setType] = useState("notebook"), [cfgs, setCfgs] = useState(base), [month, setMonth] = useState(0), [selected, setSelected] = useState(null), [gallery, setGallery] = useState(false);
  const cfg = cfgs[type], setCfg = p => setCfgs(v => ({ ...v, [type]: { ...v[type], ...p } }));
  const add = (kind) => { let e = { id: Date.now(), type: kind, x: 12, y: 18, w: 30, h: 8, size: 11, color: cfg.accent, content: kind === "text" ? "New text" : kind === "check" ? "Task" : "", bold: false }; setCfg({ elements: [...cfg.elements, e] }); setSelected(e.id) };
  const update = (id, p) => setCfg({ elements: cfg.elements.map(e => e.id === id ? { ...e, ...p } : e) }), remove = id => { setCfg({ elements: cfg.elements.filter(e => e.id !== id) }); setSelected(null) };
  const metaData = meta[type], Icon = metaData[0], elements = [["text", Type, "text"], ["check", CheckSquare, "check"], ["line", Minus, "line"], ["box", Square, "box"], ["icon", Sparkles, "icon"]];
  const exp = () => type === "notebook" ? exportNotebook(cfg) : type === "annual" ? exportAnnual(cfg) : type === "tasks" ? exportTasks(cfg) : exportWeekly(cfg);
  return <div className="app"><aside><div className="brand"><strong>dienix</strong><span>{tr(lang, "studio")}</span></div><button className="gallery" onClick={() => setGallery(true)}><Grid2X2 /> {tr(lang, "choose")}</button><label className="side">{tr(lang, "templates")}</label>{Object.entries(meta).map(([id, m]) => { let A = m[0]; return <button className={"nav " + (type === id ? "active" : "")} onClick={() => { setType(id); setSelected(null) }} key={id}><A />{tr(lang, m[1])}</button> })}<label className="side eltitle">{tr(lang, "elements")}</label><button className="nav" onClick={() => setSelected(null)}><LayoutDashboard />{tr(lang, "layout")}</button>{elements.map(([id, A, k]) => <button className="nav" onClick={() => add(id)} key={id}><A />{tr(lang, k)}</button>)}<div className="foot">dienix · DNX Lab</div></aside>
    <main><header><div><small className="eyebrow">GOODNOTES TEMPLATE GENERATOR <b>DEMO</b></small><h1>{tr(lang, metaData[1])}</h1><p>{tr(lang, metaData[2])}</p></div><div className="head-right"><div className="langs">{["en", "de", "es"].map(x => <button className={lang === x ? "on" : ""} onClick={() => setLang(x)} key={x}>{x.toUpperCase()}</button>)}</div><span className="ready">● {tr(lang, "ready")}</span></div></header>
      <div className="demo-notice"><strong>DEMO VERSION</strong><span>This is a preview of the personal Goodnotes Template Studio. Templates are generated for demonstration purposes.</span></div>
      <section className="workspace"><div className="preview"><div className="bar"><span><Sparkles /> {tr(lang, "preview")}</span><span>{type === "notebook" ? "42 pages" : type === "annual" ? `${cfg.year} · 13 pages` : type === "tasks" ? `${cfg.rows} tasks` : "7 days"}</span></div><div className="stage compact-stage"><Preview type={type} cfg={cfg} month={month}/></div>{type === "annual" && <div className="month-nav"><button onClick={() => setMonth(Math.max(0, month - 1))}><ChevronLeft /></button><span>{mn(cfg.year, month)}</span><button onClick={() => setMonth(Math.min(11, month + 1))}><ChevronRight /></button></div>}</div>
        <div className="config"><div className="bar"><span>{tr(lang, "config")}</span><Settings2 /></div><div className="scroll"><div className="presets">{Object.entries(presets).map(([n, p]) => <button onClick={() => setCfg({ accent: p[0], paper: p[1] })} key={n}><i style={{ background: p[0] }} />{n}</button>)}</div><label>Name<input value={cfg.name} onChange={e => setCfg({ name: e.target.value })} /></label><div className="two"><label>{tr(lang, "size")}<select value={cfg.size} onChange={e => setCfg({ size: e.target.value })}><option>A4</option><option>A5</option><option>Letter</option></select></label><label>{tr(lang, "orientation")}<select value={cfg.orientation} onChange={e => setCfg({ orientation: e.target.value })}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label></div><div className="two"><label>{tr(lang, "paper")}<input type="color" value={cfg.paper} onChange={e => setCfg({ paper: e.target.value })} /></label><label>{tr(lang, "accent")}<input type="color" value={cfg.accent} onChange={e => setCfg({ accent: e.target.value })} /></label></div>
          {type === "notebook" && <><label>{tr(lang, "style")}<select value={cfg.style} onChange={e => setCfg({ style: e.target.value })}><option value="ruled">Ruled</option><option value="grid">Grid</option><option value="dotted">Dotted</option><option value="blank">Blank</option></select></label><label>{tr(lang, "tabs")}<select value={cfg.tabs ? "yes" : "no"} onChange={e => setCfg({ tabs: e.target.value === "yes" })}><option value="yes">{tr(lang, "tabs")}</option><option value="no">{tr(lang, "minimal")}</option></select></label><div className="section-head">{tr(lang, "sections")}<button onClick={() => setCfg({ sections: [...cfg.sections, [`Section ${cfg.sections.length + 1}`, 10]] })}><Plus /></button></div>{cfg.sections.map((s, i) => <div className="secrow" key={i}><b>{i + 1}</b><input value={s[0]} onChange={e => setCfg({ sections: cfg.sections.map((x, j) => j === i ? [e.target.value, x[1]] : x) })} /><input type="number" value={s[1]} onChange={e => setCfg({ sections: cfg.sections.map((x, j) => j === i ? [x[0], Number(e.target.value)] : x) })} /><button onClick={() => setCfg({ sections: cfg.sections.filter((_, j) => j !== i) })}><Trash2 /></button></div>)}<div className="checks"><label><input type="checkbox" checked={cfg.cover} onChange={e => setCfg({ cover: e.target.checked })} />{tr(lang, "cover")}</label><label><input type="checkbox" checked={cfg.numbers} onChange={e => setCfg({ numbers: e.target.checked })} />{tr(lang, "numbers")}</label></div></>}
          {type === "annual" && <><div className="two"><label>{tr(lang, "year")}<input type="number" value={cfg.year} onChange={e => setCfg({ year: Number(e.target.value) })} /></label><label>{tr(lang, "week")}<select value={cfg.week} onChange={e => setCfg({ week: e.target.value })}><option value="monday">{tr(lang, "monday")}</option><option value="sunday">{tr(lang, "sunday")}</option></select></label></div><label>{tr(lang, "density")}<select value={cfg.density} onChange={e => setCfg({ density: e.target.value })}><option value="comfortable">{tr(lang, "comfortable")}</option><option value="spacious">{tr(lang, "spacious")}</option><option value="compact">{tr(lang, "compact")}</option></select></label><div className="checks"><label><input type="checkbox" checked={cfg.weeknumbers} onChange={e => setCfg({ weeknumbers: e.target.checked })} />{tr(lang, "weeknumbers")}</label><label><input type="checkbox" checked={cfg.notes} onChange={e => setCfg({ notes: e.target.checked })} />{tr(lang, "notes")}</label></div></>}
          {type === "tasks" && <><label>{tr(lang, "rows")}<input type="number" min="5" max="30" value={cfg.rows} onChange={e => setCfg({ rows: Number(e.target.value) })} /></label><div className="checks"><label><input type="checkbox" checked={cfg.priority} onChange={e => setCfg({ priority: e.target.checked })} />{tr(lang, "priority")}</label><label><input type="checkbox" checked={cfg.due} onChange={e => setCfg({ due: e.target.checked })} />{tr(lang, "due")}</label></div></>}
          {type === "weekly" && <><label>{tr(lang, "week")}<select value={cfg.week} onChange={e => setCfg({ week: e.target.value })}><option value="monday">{tr(lang, "monday")}</option><option value="sunday">{tr(lang, "sunday")}</option></select></label><div className="checks"><label><input type="checkbox" checked={cfg.notes} onChange={e => setCfg({ notes: e.target.checked })} />{tr(lang, "notes")}</label></div></>}
          <div className="elements"><div className="section-head">{tr(lang, "elements")} <span>{cfg.elements.length}</span></div>{cfg.elements.length === 0 ? <p>{tr(lang, "noElements")}</p> : cfg.elements.map(e => <button className={selected === e.id ? "sel" : ""} onClick={() => setSelected(e.id)} key={e.id}><b>{e.type}</b><span>{e.content || "Element"}</span></button>)}</div>
          {selected && cfg.elements.find(e => e.id === selected) && (() => { let e = cfg.elements.find(x => x.id === selected); return <div className="properties"><div className="section-head">{tr(lang, "selected")}<button onClick={() => remove(e.id)}><Trash2 /></button></div><label>{tr(lang, "content")}<input value={e.content} onChange={x => update(e.id, { content: x.target.value })} /></label><div className="two"><label>{tr(lang, "width")}<input type="number" value={e.w} onChange={x => update(e.id, { w: Number(x.target.value) })} /></label><label>{tr(lang, "height")}<input type="number" value={e.h} onChange={x => update(e.id, { h: Number(x.target.value) })} /></label></div></div> })()}
          <button className="export" onClick={exp}><Download /> {tr(lang, "export")}</button><small className="hint">Goodnotes-ready · internal hyperlinks included</small></div></div></section></main>
    {gallery && <div className="modal" onClick={() => setGallery(false)}><div className="modal-box" onClick={e => e.stopPropagation()}><div className="modal-head"><div><small>{tr(lang, "choose")}</small><h2>{tr(lang, "build")}</h2></div><button onClick={() => setGallery(false)}><X /></button></div><div className="cards">{Object.entries(meta).map(([id, m]) => { let A = m[0]; return <button onClick={() => { setType(id); setGallery(false) }} key={id}><A /><strong>{tr(lang, m[1])}</strong><p>{tr(lang, m[2])}</p><ChevronRight /></button> })}</div></div></div>}</div>
}
createRoot(document.getElementById("root")).render(<App />);
